import 'package:flutter/material.dart';
import 'package:flutterapp/tugas_202_20uiapp/generatediphone11prox1widget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/tugas_202_20uiapp/generatediphone11prox1widget/generated/GeneratedRoglap1Widget.dart';
import 'package:flutterapp/tugas_202_20uiapp/generatediphone11prox1widget/generated/GeneratedRoglap3Widget.dart';
import 'package:flutterapp/tugas_202_20uiapp/generatediphone11prox1widget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/tugas_202_20uiapp/generatediphone11prox1widget/generated/GeneratedStock2Widget2.dart';
import 'package:flutterapp/tugas_202_20uiapp/generatediphone11prox1widget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/tugas_202_20uiapp/generatediphone11prox1widget/generated/GeneratedLaptopASUSROGG531GTI565G1TWidget2.dart';
import 'package:flutterapp/tugas_202_20uiapp/generatediphone11prox1widget/generated/GeneratedRoglap2Widget.dart';
import 'package:flutterapp/tugas_202_20uiapp/generatediphone11prox1widget/generated/GeneratedLaptopASUSROGG531GTI565G1TWidget.dart';
import 'package:flutterapp/tugas_202_20uiapp/generatediphone11prox1widget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/tugas_202_20uiapp/generatediphone11prox1widget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/tugas_202_20uiapp/generatediphone11prox1widget/generated/GeneratedLaptopASUSROGG531GTI565G1TWidget1.dart';
import 'package:flutterapp/tugas_202_20uiapp/generatediphone11prox1widget/generated/GeneratedStock2Widget1.dart';
import 'package:flutterapp/tugas_202_20uiapp/generatediphone11prox1widget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/tugas_202_20uiapp/generatediphone11prox1widget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/tugas_202_20uiapp/generatediphone11prox1widget/generated/GeneratedProductsWidget.dart';
import 'package:flutterapp/tugas_202_20uiapp/generatediphone11prox1widget/generated/GeneratedStock2Widget.dart';

/* Frame iPhone 11 Pro / X - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 59.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 136.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 34.0,
                child: GeneratedProductsWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 97.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 117.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 117.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 363.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 117.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 111.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 88.0,
                child: GeneratedRoglap1Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 244.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 88.0,
                child: GeneratedRoglap2Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 88.0,
                child: GeneratedRoglap3Widget(),
              ),
              Positioned(
                left: 127.0,
                top: 111.0,
                right: null,
                bottom: null,
                width: 210.0,
                height: 40.0,
                child: GeneratedLaptopASUSROGG531GTI565G1TWidget(),
              ),
              Positioned(
                left: 128.0,
                top: 244.0,
                right: null,
                bottom: null,
                width: 210.0,
                height: 40.0,
                child: GeneratedLaptopASUSROGG531GTI565G1TWidget1(),
              ),
              Positioned(
                left: 127.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 210.0,
                height: 40.0,
                child: GeneratedLaptopASUSROGG531GTI565G1TWidget2(),
              ),
              Positioned(
                left: 127.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 26.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: 127.0,
                top: 306.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 26.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 127.0,
                top: 173.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 26.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 143.0,
                top: 447.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 14.0,
                child: GeneratedStock2Widget(),
              ),
              Positioned(
                left: 143.0,
                top: 313.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 14.0,
                child: GeneratedStock2Widget1(),
              ),
              Positioned(
                left: 143.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 14.0,
                child: GeneratedStock2Widget2(),
              )
            ]),
      ),
    ));
  }
}
